name: Build

on:
  workflow_dispatch:

jobs:
  build-windows:
    strategy:
      matrix:
        arch: [Win32, x64]
        config: [Release]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: TheMrMilchmann/setup-msvc-dev@v4
        with:
          arch: ${{ matrix.arch == 'x64' && 'amd64' || 'x86' }}

      - name: Generate build files
        run: cmake -G Ninja -DCMAKE_BUILD_TYPE=${{ matrix.config }} -B build -S .

      - name: Build
        run: cmake --build build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: samp-gps-win-${{ matrix.arch }}-${{ matrix.config }}
          path: build/GPS.dll

  build-linux:
    strategy:
      matrix:
        bit: [32, 64]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install packages
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build g++-multilib libstdc++6:i386 libc6:i386

      - name: Generate build files
        run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DGPS_BUILD_32BIT=${{ matrix.bit == 32 && 'ON' || 'OFF' }}

      - name: Build
        run: cmake --build build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: samp-gps-linux-${{ matrix.bit == 32 && 'i386' || 'x86_64' }}-Release
          path: build/GPS.so
